<div class="container">
    <div class="row py-4">
        <div class="col-md-12 p-2">
            <h1>Gebrauchtmaschinen Ratgeber</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <ul>
                <?php
                foreach($aItems as $faq) {
                    ?>
                    <li>
                        <a href="/faq/<?=$faq->getTextField('url')?>">
                            <?=$faq->getLabel()?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>

    <div class="row py-4">
        <div class="col-md-12 py-4">
        </div>
    </div>
</div>