<div class="container">
    <div class="row py-4">
        <div class="col-md-12 p-2">
            <h1>Faq</h1>
        </div>
    </div>

    <?php foreach($aItems as $faq) { ?>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <?=$faq->getLabel()?>
                    </div>
                    <div class="card-body">
                        <?=$faq->getTextField('description')?>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>

    <div class="row py-4">
        <div class="col-md-12 py-4">
        </div>
    </div>
</div>
