<div class="container">
    <div class="row" style="background: #e9ecef;">
        <div class="container">
            <nav aria-label="breadcrumb" style="background: transparent;">
                <ol class="breadcrumb py-2 my-0 px-0 mx-0">
                    <li class="breadcrumb-item">
                        <a href="/ratgeber">
                            <i class="fas fa-home"></i> <?=$this->translate('Ratgeber')?>
                        </a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row py-4">
        <div class="col-12">
            <h1><?=$faq->getLabel()?></h1>
            <p>
                <?=$faq->getTextField('description')?>
            </p>
        </div>
    </div>
</div>