<h2>Edit Book</h2>

<?= $this->partial('partial/basicform', ['sFormName'=>$sFormName,'oItem'=>$oBook]); ?>

<?php
/**
 * @addedtoskeleton
 * @requires 1.0.0
 * @campatibleto master-dev
 */
?>
<script>
$(function() {
    // listen on isbn blur
    $('input[name="<?=$sFormName?>_isbn"]').on('blur',function() {
        var sISBN = $(this).val();

        // check if value is in isbn10 format
        if (sISBN.length == 10 && $.isNumeric(sISBN))
        {
            var iChecksum = 0;

            // isbn10 to isbn13 algorithm
            var sISBN13 = "978" + sISBN.substring(0, 9);
            for (i = 0; i < sISBN13.length; i++) {
                iChecksum += (i%2)?parseInt(sISBN13[i]*3):parseInt(sISBN13[i]);
            }
            iChecksum = (10 - (iChecksum%10)) %10;
            sISBN13 = sISBN13 + String(iChecksum);

            // write new isbn13
             $('input[name="<?=$sFormName?>_isbn13"]').val(sISBN13);
        }
    });
});
</script>
<?php
/**
 * @addedtoskeletonend
 */
?>